### ISSUE TITLE
DISPLAY problem on remote server

### ISSUE THREAD

**Issue by leey127** [ucsdarclab/dVRL#10]
Hello!
I'm trying to get this running on a remote Ubuntu server. I connected to the server by mobaXterm, as a normal user with sudo privileges. I followed the first method in this [guide](http://wiki.ros.org/docker/Tutorials/GUI), running

`docker run -it --rm --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --vol                                                                  ume="/tmp/.X11-unix:/tmp/.X11-unix:rw" vrep_ee_pick`

And the error is 

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QXcbConnection: Could not connect to display localhost:10.0
/app/V-REP/vrep.sh: line 33:    13 Aborted                 (core dumped) "$dirna                                                                  me/$appname" "${PARAMETERS[@]}"`

The error was similar to several existing issues, but none of the solutions worked. It might be something about the remote display since there're no graphical interfaces on a server. I found some other ways to get a GUI app running in docker on a remote server, like [this](https://blog.yadutaf.fr/2017/09/10/running-a-graphical-app-in-a-docker-container-on-a-remote-server/).

And I got

`XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
MoTTY X11 proxy: Unsupported authorisation protocol
QXcbConnection: Could not connect to display :10
/app/V-REP/vrep.sh: line 33:    14 Aborted                 (core dumped) "$dirname/$appname" "${PARAMETERS[@]}"
[1]+  Done                    socat TCP4:localhost:60${DISPLAY_NUMBER} UNIX-LISTEN:/tmp/.X11-unix/X${DISPLAY_NUMBER}`

I'm just a beginner in Reinforcement Learning and don't know much about the Linux server. It seems that X11 runs well on my server since I can see a clock window after I run `xclock`. And nvidia-docker has been well installed too, since there's no error report when running `docker run --runtime nvidia nvidia/cuda:10.0-base nvidia-smi`.

Have someone successfully run this on a remote server? Many thanks!

**Comment by bango123** [comment]
To be honest with you I have never tried this. I believe you will have to modify lines 51 to 63 in PsmEnv.py file to match the link you shared. I would test other GUI based dockers first to help debug or run lines 51-63 in PSMEnv.py in a separate python file.

**Comment by leey127** [comment]
Thank you very much! I've tried to modify lines 51 to 63 in PsmEnv.py but it didn't work. Maybe it was because I don't know how to modify it correctly. 

But I succeeded to link Vrep simulation on my Windows PC, according to what you suggested in other issues. Being very new to Reinforcement Learning, I want to ask can I train agents on Windows platform using this platform?

**Comment by bango123** [comment]
This is purely a RL environment in the OpenAI gym format. So any other training procedure that is compatible with OpenAI gym should work.

**Comment by luiscarlosgph** [comment]
The Python module **dockerl** is intended to solve this problem. 

You can install it running:
```
python3 -m pip install dockerl --user
```
Then, to run a container with X11 support:
```bash
$ python3 -m dockerl.run --image <image name> 
```
If you want CUDA support (NVIDIA runtime), you can also run:
```bash
$ python3 -m dockerl.run --image <image name> --nvidia 1
```

If you want to launch containers from your Python code, as in PsmEnv.py, then:
```python
import dockerl
dl = dockerl.DockerLauncher()
container = dl.launch_container('put_the_name_of_your_image_here')
print(container.id)
```

**dockerl** requires that the SSH server running in the remote computer has the option ```X11UseLocalhost no``` set in ```/etc/ssh/sshd_config```.

For more details, check [the GitHub of the dockerl Python module](https://github.com/luiscarlosgph/docker-with-graphics).
