### ISSUE TITLE
Questions about log when start

### ISSUE THREAD

**Issue by ljjTYJR** [ucsdarclab/dVRL#11]
Hello, When I use alg='her' to train the model, I meet with the log as below:
> Failed to find RCM_PSM1
64
Failed to find J1_PSM1
64
Failed to find J2_PSM1
64
Failed to find J3_PSM1
64
Failed to find J1_TOOL1
64
Failed to find J2_TOOL1
64
Failed to find J3_dx_TOOL1
64
Failed to find J3_sx_TOOL1
64
Failed to find J2_virtual_TOOL1
64
Failed to find J3_dx_tip_TOOL1
64
Failed to find J3_sx_tip_TOOL1
64
Failed to find IK_target_dx_PSM1
64
Failed to find IK_target_sx_PSM1
64
Failed to find EE_virtual_TOOL1
64
Failed to find Target_PSM1
64
Failed to find customizableTable_tableTop
64

I am sure I connect to the vrep, and the correct environment of _Reach_, Is there any thing need to be noticed?

**Comment by bango123** [comment]
Was this connected through modifications in the PSMEnv.py file? Also, the baselines HER implementation opens/closes the environment many times for initialization. Please take a look at the function close() in PSMEnv.py

```
def close(self):
	if self.viewer is not None:
 		plt.close(self.viewer.number)
 		self.viewer = None
	vrep.simxFinish(self.clientID)
 	self.container.kill()
```

By default, the close function runs simxFinish which closes the communication with the simulation. I recommend either using a different implementation of HER which does not construct deconstruct the environment. An "experimental" solution may be removing the "prep.simxFinish(self.clientID)"... Idk what will happen though.

**Comment by ljjTYJR** [comment]
Yeah, I use the baselines her to train the model;
The problem I mention above only appears when I run the command to train.
The vrep does not seem to stop then restart when a new epoch starts, 
However! when I comment out "vrep.simxFinish(self.clientID)" and use baselines-her to train the model, Its success rate finally greater than 0(before, the rate is always 0...) I will consider why this happens...
Thanks!

**Comment by ljjTYJR** [comment]
Since there exists success rate, If it can not promise 100% success rate, does it really can be applied to the real robot?

**Comment by bango123** [comment]
I only tested the converged policies at close to 100% in my experiments. I do not know about the transfer-ability in the non-converged policies and if they act similar in the real world vs simulation.
