### ISSUE TITLE
How is the grasping controlled?

### ISSUE THREAD

**Issue by Cladett** [ucsdarclab/dVRL#12]
Hello,
I have been playing around with the _pick_ task. And I have few questions...

1) 
Based on what I have understood, the object position is controlled by the dummies. So also the grasp refers to it.
What is not clear to me is why there is no threshold that defines when the grasping is successful or not. 
If i have understood correctly, inside _PsmEnv_positioning.py_ the **line 113** 
_self.obj.isGrasped(ignoreError = True, initialize= True)_
Here i am basically declaring this so that the object **isGrasped** for all the methods inside the file rather than __reset_sim()_ where in line 268 **removeGrasped** is called correct?

2) In simObjects.py the are the definition of  removeGrasped adn isGrasped 
From what i can understand  
> _removeGrasped_ sets the object parentless since parenthandle=-1
> _isGrasped_ always returns **false** because has the control with not(object is parentless) 
Is this correct?
Opening the .ttt file with vrep i can see the the obj is decleare already without any parents.
So I am a bit confused on why the control of the grasp is based on checking the parent of the object.

3) Once the EE actually grasps the object. It's not clear to me how the movement of the object is actuated. Because inside _set_action(action) the only position that is controlled/set is the one of the EE while setObjectPosition is never called. So how does the object movements take place?

Thanks,
Cheers

**Comment by bango123** [comment]
The grasping simulation is programmed into the V-REP scene and done in the following way:

1. The object is first detected by the proximity sensor to indicate the object is in the gripper
2. Then the gripper value must be less than a set threshold to declare it is grasping
3. If both 1 and 2 hold true, the object is then rigidly attached to the kinematic chain of the end-effector.

So in the python code, only the parent object needs to be checked to see if the object is grasped or not.

**Comment by Cladett** [comment]
Thank you for you answer.

Where does point 1, 2, 3 are implemented in the code? 
Mainly, where is the set threshold of point 2 declared in the code?

So based on point 3 once the object is grasped the the arm becomes the parent which is why you check that for checking the grasp ?

Thank you

**Comment by bango123** [comment]
Yes that is correct. And the code for all of this is in the V-REP *.ttt files which is located in dVRL/dVRL_simulator/environments/pick_ee_dockerfile. Then it should be a child script in the PSM model. I forget which exact component it is a part of, and I can check later if you do not find it (I am unable to check right now).

**Comment by Cladett** [comment]
Thank you very much.
I found them!
