### ISSUE TITLE
How can I change the type of observation_space to 'Box'?

### ISSUE THREAD

**Issue by leey127** [ucsdarclab/dVRL#14]
Hello

I want to test DDPG+HER algorithm in dVRLReach env. When I ran the following code
```
env_reach = gym.make("dVRLReach-v0")
state_dim = env_Reach.observation_space.shape[0]
```
I got a 'NoneType' state_dim. After some digging, I found that the type of _observation_space_ of the environment was 'Dict' (Line 120-124 in _PsmEnv.py_). So, can I change these lines to make this env  suitable for ddpg testing? Changing the type of observation_space or any other way?

**Comment by ljjTYJR** [comment]
dict type is used for _HER_
