### ISSUE TITLE
Question about setting the target position

### ISSUE THREAD

**Issue by neriniccolodei** [ucsdarclab/dVRL#16]
Dear @bango123, 

From what I have understood, setting the target position is done like this.

1) we randomize x and y in a range of +- `target_range`, z between 0 and +`target_range`. Then we add a `target_offset` and expand the vector with a 4th element equal to 0, such 4x1 vector is `deltaGoal_b_homogeneous`. 
2) the previous vector is premultiplied by `b_T_table`. Considering the 4th element is 0, the result of this is simply a rotation of [x,y,z], with fixed direction cosines given by how reference frame of table is set with respect to the base frame. Printing the matrix, it seems like its a simple revolution about z axis, which is the same in the 2 frames. 
3) you lower the randomized vector by approximately 16 cm, which is the height of initial_pos projected on table relative to the RCM, center of the base frame, by saying that goal is the previously rotated vector + pos_ee_projectedOnTable.
4) you set such position relative to base frame. 

Now, I don't really get the point of step 2. Why would you rotate the x,y,z vector?  

Best regards, Neri

**Comment by bango123** [comment]
The target offsets is defined relative to the table, so a sampled goal is likewise sampled in the table coordinate frame. So step 2 transforms it to the base frame of the robot.

**Comment by neriniccolodei** [comment]
Thank you. So what you do is saying ok these are my x,y,z coordinates in the table frame, we rotate them so they are relative to the base frame, we lower the point, we set it. Am I right?

If I may ask a further question, regarding where the robot looks for the target. I have not understood which steps I should take if I wanted to recenter the search space. 
Also, I am not sure it only depends on the target range and initial_pos. With search space, I mean the area in space where the robot looks for the target during training. 

In my scenario, I would like to do the following: I have a cuboid, I want to randomize its position and orientation and do so via its center. I have 2 targets on opposite sides of his top face. Those will likely be out of target range, considering I use such a range to randomize the cuboid's position. 
How do I tell the robot to search for such targets in a bigger search space? 
I am missing the point where target_range or any other variable in your code defines such a search space, if there's any.

Best regards, Neri

**Comment by bango123** [comment]
The bounds of where the robot may reach are defined in lines 184-186 

```
# #Make sure the new pos doesn't go out of bounds!!!
		upper_bound = self.initial_pos + self.target_range + 0.01
		lower_bound = self.initial_pos - self.target_range - 0.01
```

Oh and please note my previous edit. I miss-spoke and only the target offset is defined relative to the table as this offset defines how high off the table the goal should be.

**Comment by neriniccolodei** [comment]
Thank you! 

> Oh and please note my previous edit. I miss-spoke and only the target offset is defined relative to the table as this offset defines how high off the table the goal should be.

I understand what you mean, however I just saw target_offset as an upward translation from end effector projected on table, that's why I didn't think about the table ref. frame, because that already lowers down to table height. 

Q1: So am I right to think of the space where the target is randomized as a box of dimensions +- target_range along x-y plane and height 0 (table top) to target_range along z, with z axis of the base frame passing by its center? Like is it a box centered in (0,0) in base frame  x-y wise? The rotation of my first comment kinda tricks my mind in figuring where the randomization space fits in space! 

> `# #Make sure the new pos doesn't go out of bounds!!!
		upper_bound = self.initial_pos + self.target_range + 0.01
		lower_bound = self.initial_pos - self.target_range - 0.01`

Q2: So do these bounds define where to search by limiting the robot? 
I have played with the reach task and I was wondering why the limit of the translational joint (the yellow guide) is so short, the black arm carrying the LND elongates way less than what it might.

Best regards, Neri

**Comment by bango123** [comment]
> Q1: So am I right to think of the space where the target is randomized as a box of dimensions +- target_range along x-y plane and height 0 (table top) to target_range along z, with z axis of the base frame passing by its center? Like is it a box centered in (0,0) in base frame x-y wise? The rotation of my first comment kinda tricks my mind in figuring where the randomization space fits in space!

Yes. And to your point, I can believe the rotation is not necessary. 

> Q2: So do these bounds define where to search by limiting the robot?
I have played with the reach task and I was wondering why the limit of the translational joint (the yellow guide) is so short, the black arm carrying the LND elongates way less than what it might.

These bounds limit the end-effector space, but there are also joint limits. I typically defined the end-effector space to be a small region so not to run into any joint limits. I believe all the joint limits are realistic? But please let me know if you find some inconsistencies.

**Comment by neriniccolodei** [comment]
> Yes. And to your point, I can believe the rotation is not necessary.

Great!

> These bounds limit the end-effector space, but there are also joint limits. I typically defined the end-effector space to be a small region so not to run into any joint limits. I believe all the joint limits are realistic? But please let me know if you find some inconsistencies.

I don't know the real limits, just judged by looks and for some cases it looked off. For example, I am trying to understand the limits empirically by passing a certain vector position for the target and seeing if the LND reaches it with a script equal to sample_env's one. Sometimes it looks like it really could stretch a bit more than what it actually does. However, it might be just that its out of bound! Do you agree that this limit I am empirically searching will likely correspond to the bounds you've set? I hadn't thought about that.
