### ISSUE TITLE
Issue when activating dynamics

### ISSUE THREAD

**Issue by neriniccolodei** [ucsdarclab/dVRL#18]
Dear @bango123,

I can't understand why I am having these issues when running your simulation (or mine) with dynamics enabled and randomize_ee = True. 

In your case, the cylinder seems to go out of the yellow guide. 
In my case, what happens is quite more disastrous, since the space my EE can randomize in is bigger.

It basically starts in configurations that are non-sense and loses the focus on targets, trying to reach them where they are not. 
Black box is for privacy on the content of the simulation.

Best regards

![original2](https://user-images.githubusercontent.com/62433425/85410654-a607a800-b567-11ea-966a-8a9e87921f16.png)

<img width="718" alt="Schermata 2020-06-23 alle 15 38 22" src="https://user-images.githubusercontent.com/62433425/85410636-a1db8a80-b567-11ea-9df8-e5fc1883e891.png">

**Comment by bango123** [comment]
Hello! The dynamics flag is something I put in in case of future efforts. Unfortunately, I was unable to get the dynamics parameters to stay stable... I think using different physics engines gave different results and turning up the internal scaling factor for them.

**Comment by neriniccolodei** [comment]
Thank you for the tip, I will try to improve it with different physics engines and scaling factors.
