### ISSUE TITLE
Question about reset call in Reach environment

### ISSUE THREAD

**Issue by SilviaZirino** [ucsdarclab/dVRL#20]
Hello,

I modified the Reach environment to train the agent with DQN, and I initially set "done=True" once the end-effector has reached the target, because I thought that the episode should end with the conclusion of the reach task.
Thus, when training with DQN, the reset function is called both when an episode ends and when the target is reached.

Looking more carefully at the original version of dVRL Reach, I noticed that "done = True" is called only when the number of time-steps equals or is grater than the maximum number of time-steps and, consequenly, the environment is reset only in this case.

So my question is: why don't you reset the environment when the target is reached even though the task is completed? Is it because you wanted to keep the episode length constant?

Many thanks in advance!

**Comment by bango123** [comment]
I am so sorry for the crazy late response. The notification must have slipped through my emails somehow. The reason why I do not terminate early is I found this helps with training (converges slightly faster). I don't think it's absolutely necessary.
