### ISSUE TITLE
Can this run on a computer with AMD GPU?

### ISSUE THREAD

**Issue by neriniccolodei** [ucsdarclab/dVRL#7]
Dear reader, 

I am trying to work on these environments to develop new RL algorithms, but I am stuck at setting things up because my Mac has issues already at installing Ubuntu, it freezes. 

Before moving on with this machine I was wondering if any of this is going to work with a MacBook Pro with AMD graphics. Like which NVIDIA driver would I even install? 

Is there any way to skip step 2 and not use GPU acceleration? Is there AMD compatibility?

Best regards,
Neri

**Comment by bango123** [comment]
So the nvidia step is to give the docker access to the display. This is needed to run v-rep in the docker.

What you can do instead is run the v-rep environment like normal (not in a docker) and remove the docker run commands in PSMEnv. Please see my comments in a previous issue: https://github.com/ucsdarclab/dVRL/issues/3
